# Generated by Django 6.0.1 on 2026-02-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=100)),
                ('fees', models.IntegerField()),
                ('duration', models.IntegerField(choices=[(3, '3 months'), (6, '6 months'), (12, '12 months')], default=3)),
            ],
            options={
                'db_table': 'course',
            },
        ),
    ]
