# Generated by Django 6.0.1 on 2026-02-12 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeptName', models.CharField(max_length=100)),
                ('location', models.IntegerField(choices=[(0, 'Ground Floor'), (1, 'First Floor'), (2, 'Second Floor')])),
                ('Deptincharge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'db_table': 'department',
            },
        ),
    ]
